# -*- coding: utf-8 -*-
"""
Module Drills — 50 questions per module (Modules 1-3 here, 4-6 in part B).
Format: list of (module_num, module_title, weight, [questions]).
Each question: {"type","q","opts"(list of (L,text) or None),"ans","exp"}.
Designed to NOT overlap with Sets 1-3.
"""

M1 = ("Design Applications", 14, [
 {"type":"mcq","q":"Which prompt component is primarily responsible for setting the model's persona or role?",
  "opts":[("A","Instruction"),("B","Context"),("C","Input"),("D","Output Format")],"ans":"B",
  "exp":"Persona/role and background belong to the Context component; the Instruction states the task."},
 {"type":"mcq","q":"You append 'Let's think step by step' with no examples. This is:",
  "opts":[("A","Few-shot prompting"),("B","Zero-shot chain-of-thought"),("C","Fine-tuning"),("D","RLHF")],"ans":"B",
  "exp":"A reasoning trigger with no exemplars is zero-shot CoT."},
 {"type":"mcq","q":"A task needs the model to mimic a very specific JSON structure it keeps getting wrong. The cheapest fix is usually:",
  "opts":[("A","Add 1-3 few-shot examples of the exact format"),("B","Fine-tune"),("C","Switch architectures"),("D","Raise temperature")],"ans":"A",
  "exp":"Few-shot examples teach format patterns cheaply without training."},
 {"type":"mcq","q":"Which model family reads the entire input bidirectionally and is NOT autoregressive?",
  "opts":[("A","Decoder-only"),("B","Encoder-only"),("C","Diffusion"),("D","Mixture-of-experts decoder")],"ans":"B",
  "exp":"Encoder-only models use bidirectional attention and aren't autoregressive generators."},
 {"type":"mcq","q":"For open-ended text generation, the natural architecture is:",
  "opts":[("A","Encoder-only"),("B","Decoder-only (autoregressive)"),("C","A classifier head"),("D","A clustering model")],"ans":"B",
  "exp":"Autoregressive decoders generate text token by token."},
 {"type":"mcq","q":"The ReAct loop consists of which repeating triple?",
  "opts":[("A","Plan, Act, Reflect"),("B","Thought, Action, Observation"),("C","Encode, Decode, Score"),("D","Retrieve, Rank, Read")],"ans":"B",
  "exp":"ReAct interleaves Thought → Action → Observation."},
 {"type":"mcq","q":"Which agentic pattern generates a full multi-step plan up front before executing?",
  "opts":[("A","ReAct"),("B","Planning"),("C","Pure tool-use"),("D","Reflexion only")],"ans":"B",
  "exp":"The Planning pattern produces an explicit plan, then executes."},
 {"type":"mcq","q":"A request requires parallel, specialized sub-agents whose outputs are merged. Best pattern:",
  "opts":[("A","Single ReAct agent"),("B","Multi-agent supervisor"),("C","Zero-shot prompt"),("D","Encoder classifier")],"ans":"B",
  "exp":"Heterogeneous/parallel specialization is the multi-agent supervisor signal."},
 {"type":"mcq","q":"Which Agent Brick turns documents into a citing Q&A chatbot?",
  "opts":[("A","Information Extraction"),("B","Knowledge Assistant"),("C","Supervisor"),("D","Custom LLM")],"ans":"B",
  "exp":"Knowledge Assistant = grounded Q&A with citations."},
 {"type":"mcq","q":"Which Agent Brick converts unstructured PDFs into structured JSON fields?",
  "opts":[("A","Knowledge Assistant"),("B","Information Extraction / Document Intelligence"),("C","Genie"),("D","Supervisor")],"ans":"B",
  "exp":"Information Extraction/Document Intelligence yields structured data from unstructured docs."},
 {"type":"mcq","q":"A Supervisor agent system can include at most how many agents?",
  "opts":[("A","5"),("B","10"),("C","20"),("D","Unlimited")],"ans":"C",
  "exp":"The documented hard limit is 20 agents per supervisor system."},
 {"type":"mcq","q":"In LangChain, the component that fetches relevant documents is the:",
  "opts":[("A","Output Parser"),("B","Retriever"),("C","Prompt Template"),("D","Callback")],"ans":"B",
  "exp":"The Retriever pulls context from a vector store/index."},
 {"type":"mcq","q":"Which is the correct order for a basic RAG chain?",
  "opts":[("A","LLM → Retriever → Prompt → Parser"),("B","Retriever → Prompt → LLM → Parser"),("C","Prompt → Retriever → Parser → LLM"),("D","Parser → LLM → Prompt → Retriever")],"ans":"B",
  "exp":"Retrieve, build prompt with context, generate, then parse."},
 {"type":"mcq","q":"Daily-changing facts must be reflected without retraining. Choose:",
  "opts":[("A","Fine-tuning"),("B","RAG"),("C","Prompt-only memorization"),("D","Distillation")],"ans":"B",
  "exp":"RAG injects current data at query time; fine-tuning bakes stale facts."},
 {"type":"mcq","q":"Fine-tuning is the better tool primarily for:",
  "opts":[("A","Frequently changing facts"),("B","Style, tone, format, and task behavior adaptation"),("C","Real-time data"),("D","Access control")],"ans":"B",
  "exp":"Fine-tuning adapts behavior/format, not volatile facts."},
 {"type":"mcq","q":"Which memory keeps only the last N turns in the prompt?",
  "opts":[("A","Windowed/buffer memory"),("B","Full-history injection"),("C","Vector long-term store"),("D","No memory")],"ans":"A",
  "exp":"Windowed buffer retains recent turns only."},
 {"type":"mcq","q":"A fact-store (knowledge-triple) memory is preferred over full history mainly to:",
  "opts":[("A","Increase token cost"),("B","Keep only salient durable facts and reduce tokens"),("C","Remove the system prompt"),("D","Disable retrieval")],"ans":"B",
  "exp":"It stores salient facts, lowering tokens while preserving key info."},
 {"type":"mcq","q":"For multilingual translation that reads the full input before producing output, the classic fit is:",
  "opts":[("A","Encoder-only"),("B","Decoder-only"),("C","Encoder-decoder / Seq2Seq"),("D","Embedding model")],"ans":"C",
  "exp":"Seq2Seq encodes fully then decodes — the canonical translation design."},
 {"type":"mcq","q":"Which input/output pair is well-aligned for an encoder-only model?",
  "opts":[("A","Prompt → long generated essay"),("B","Text → category label"),("C","Image → caption"),("D","Question → multi-step plan")],"ans":"B",
  "exp":"Encoder-only excels at classification (text → label)."},
 {"type":"mcq","q":"The MAIN advantage of Agent Bricks over custom-coded agents is:",
  "opts":[("A","Maximum control of control-flow"),("B","Speed-to-production with built-in governance/eval"),("C","Lower token price"),("D","No need to evaluate")],"ans":"B",
  "exp":"Bricks trade flexibility for fast, governed production readiness."},
 {"type":"mcq","q":"Custom-coded agents (LangGraph) are justified when you need:",
  "opts":[("A","Cyclic graphs, conditional branching, custom state/HITL the builder can't express"),("B","Built-in tracing"),("C","Auto benchmarks"),("D","Standard doc Q&A")],"ans":"A",
  "exp":"Bespoke control-flow beyond the managed builder justifies custom code."},
 {"type":"mcq","q":"A vague Output Format like 'be brief' causes inconsistent lengths. The fix is to:",
  "opts":[("A","Add a measurable constraint (e.g., ≤2 sentences)"),("B","Remove the Instruction"),("C","Lower temperature to 0 only"),("D","Add more context")],"ans":"A",
  "exp":"Subjective words don't bound length; specify a measurable limit."},
 {"type":"mcq","q":"Image-in, text-out captioning requires a:",
  "opts":[("A","Multimodal vision-language model"),("B","BERT classifier"),("C","Pure embedding model"),("D","Seq2Seq translator")],"ans":"A",
  "exp":"Captioning needs a multimodal model."},
 {"type":"mcq","q":"Which is the strongest reason to decompose a complex task into stages?",
  "opts":[("A","It always reduces cost"),("B","Each stage can use the right tool/model and be optimized/tested independently"),("C","It removes the need for prompts"),("D","It guarantees no hallucination")],"ans":"B",
  "exp":"Decomposition maps sub-tasks to appropriate components, improving optimization/testing."},
 {"type":"mcq","q":"A router that classifies intent and sends queries to specialist chains is an example of:",
  "opts":[("A","A single static prompt"),("B","A routing/dispatch design"),("C","Quantization"),("D","Tokenization")],"ans":"B",
  "exp":"A routing layer dispatches to specialized handlers."},
 {"type":"mcq","q":"The Tool-Use pattern means:",
  "opts":[("A","Tools always run in fixed order"),("B","The model decides whether/which tool to call"),("C","No tools are used"),("D","Tools replace the model")],"ans":"B",
  "exp":"Tool-Use lets the model choose to invoke tools dynamically."},
 {"type":"mcq","q":"Which is NOT a valid reason to choose multi-agent over single-agent?",
  "opts":[("A","Independent parallel subtasks"),("B","Distinct specialized expertise per subtask"),("C","Simply wanting fewer LLM calls"),("D","Coordinating heterogeneous tools")],"ans":"C",
  "exp":"Multi-agent typically adds calls/overhead; fewer-calls is not a reason for it."},
 {"type":"mcq","q":"Supervisor 'long-running task mode' helps by:",
  "opts":[("A","Increasing temperature"),("B","Breaking tasks into multiple request/response cycles to avoid timeouts"),("C","Removing tools"),("D","Disabling tracing")],"ans":"B",
  "exp":"Task continuation across cycles avoids timeouts on long tasks."},
 {"type":"mcq","q":"AI Search index subagents in a Supervisor support which index type?",
  "opts":[("A","Only Delta Sync indexes"),("B","Only CSV"),("C","Any database"),("D","No indexes")],"ans":"A",
  "exp":"AI Search subagents support Delta Sync indexes."},
 {"type":"mcq","q":"To resist prompt injection by design, you should:",
  "opts":[("A","Trust all user input"),("B","Separate/delimit untrusted input and keep system instructions authoritative"),("C","Raise temperature"),("D","Remove guardrails")],"ans":"B",
  "exp":"Delimiting untrusted input and authoritative system roles reduce injection risk."},
 {"type":"mcq","q":"Few-shot examples have which trade-off?",
  "opts":[("A","They reduce tokens"),("B","They raise token cost/latency and can hit context limits"),("C","They eliminate the need for instructions"),("D","They only help classification")],"ans":"B",
  "exp":"More examples cost more tokens and can overflow context."},
 {"type":"mcq","q":"Which best describes a LangChain 'chain'?",
  "opts":[("A","A GPU cluster"),("B","A composed pipeline where each step's output feeds the next"),("C","A blockchain"),("D","An embedding")],"ans":"B",
  "exp":"A chain composes modular steps into a pipeline."},
 {"type":"mcq","q":"A code-generation feature prioritizing quality across languages should use:",
  "opts":[("A","An embedding model"),("B","A code-specialized LLM"),("C","An encoder-only model"),("D","A diffusion model")],"ans":"B",
  "exp":"Code-specialized LLMs are tuned for multi-language code quality."},
 {"type":"mcq","q":"Which describes 'grounding' in design?",
  "opts":[("A","Lowering GPU clocks"),("B","Tying outputs to authoritative retrievable evidence"),("C","Random sampling"),("D","Compressing the model")],"ans":"B",
  "exp":"Grounding connects responses to authoritative evidence."},
 {"type":"mcq","q":"When ordering of tool calls is a hard business rule, enforce it via:",
  "opts":[("A","Prompt wording only"),("B","A deterministic workflow/guard, not model discretion"),("C","Temperature"),("D","More tools")],"ans":"B",
  "exp":"Critical ordering should be deterministic, not left to the model."},
 {"type":"mcq","q":"Genie (AI/BI) is best for:",
  "opts":[("A","Natural-language analytics over governed tables"),("B","Image generation"),("C","OCR"),("D","Embedding training")],"ans":"A",
  "exp":"Genie answers questions over tables (text-to-SQL style)."},
 {"type":"mcq","q":"Which is a design risk of reusable prompt templates with user input?",
  "opts":[("A","Lower latency"),("B","Prompt injection via untrusted interpolation"),("C","Smaller index"),("D","Better citations")],"ans":"B",
  "exp":"Interpolating untrusted input risks injection."},
 {"type":"mcq","q":"A 50M/day fixed-label classification feature with strict latency should use:",
  "opts":[("A","A large decoder with few-shot"),("B","A fine-tuned encoder-only classifier"),("C","A multi-agent system"),("D","A diffusion model")],"ans":"B",
  "exp":"Encoder-only classifiers give lowest latency/cost at scale for fixed labels."},
 {"type":"mcq","q":"Adding many tools to one agent can hurt accuracy because:",
  "opts":[("A","It reduces the action space"),("B","It enlarges the action space/prompt and causes tool confusion"),("C","It removes the LLM"),("D","It lowers temperature")],"ans":"B",
  "exp":"Too many tools cause selection errors and context bloat."},
 {"type":"mcq","q":"Which combination handles 'remember durable facts within a tight token budget' best?",
  "opts":[("A","Full history"),("B","Window + fact store"),("C","No memory"),("D","Fine-tune per turn")],"ans":"B",
  "exp":"A window plus a fact store balances coherence and cost."},
 {"type":"mcq","q":"Persistent agent memory on Databricks is provided via:",
  "opts":[("A","Lakebase"),("B","Photon"),("C","DBFS root"),("D","Koalas")],"ans":"A",
  "exp":"Agent Bricks gives persistent memory via Lakebase in the lakehouse."},
 {"type":"open","q":"Explain why choosing a single ReAct agent does NOT by itself guarantee tenant data isolation, and where isolation must be enforced.",
  "opts":None,"ans":"See explanation",
  "exp":"Any agent's prompt-level reasoning can be subverted by injection, so isolation must be enforced at the data/retrieval layer (Unity Catalog row/column security, scoped functions) so unauthorized data is never retrievable, independent of the agent pattern."},
 {"type":"open","q":"Give a scenario where you'd deliberately combine RAG and fine-tuning, and the division of labor.",
  "opts":None,"ans":"See explanation",
  "exp":"E.g., a clinical assistant fine-tuned for tone/structured output/safe refusals (HOW it answers) combined with RAG over the latest guidelines (WHAT current evidence it uses). Fine-tuning handles behavior/format; RAG handles volatile facts."},
 {"type":"open","q":"Contrast when Planning outperforms a Supervisor and vice versa.",
  "opts":None,"ans":"See explanation",
  "exp":"Planning wins for ordered interdependent steps within one competence (simpler, cheaper plan-then-execute). Supervisor wins when subtasks need different specialized agents/tools or can run in parallel and must be coordinated/merged."},
 {"type":"mcq","q":"Which is TRUE about decoder-only models and classification?",
  "opts":[("A","They cannot classify at all"),("B","They can classify via prompting but are generally slower/pricier than encoder-only for high-volume fixed-label tasks"),("C","They are always best for classification"),("D","They are non-autoregressive")],"ans":"B",
  "exp":"Decoders can classify via prompts but encoder-only is more efficient at scale."},
 {"type":"mcq","q":"A 'specification trigger' question describing a comparison table wants you to:",
  "opts":[("A","Describe it in prose only"),("B","Recognize it as a request for structured output"),("C","Ignore format"),("D","Use higher temperature")],"ans":"B",
  "exp":"A named artifact like a comparison table implies structured output."},
 {"type":"mcq","q":"Which is the best first step (cheapest) to reduce hallucination before RAG?",
  "opts":[("A","Fine-tune"),("B","Add grounding context + 'say I don't know'"),("C","Switch to multi-agent"),("D","RLHF")],"ans":"B",
  "exp":"Grounding context is the cheapest first intervention."},
 {"type":"mcq","q":"The Custom LLM Brick is for:",
  "opts":[("A","Multi-agent orchestration"),("B","Specializing an LLM for custom text tasks (summarize/classify/transform)"),("C","Document Q&A"),("D","Analytics over tables")],"ans":"B",
  "exp":"Custom LLM Brick specializes a model for custom text tasks."},
 {"type":"mcq","q":"Which statement about autoregressive generation is correct?",
  "opts":[("A","All tokens are produced simultaneously"),("B","Each token is conditioned on previously generated tokens"),("C","It uses bidirectional attention"),("D","It cannot generate text")],"ans":"B",
  "exp":"Autoregressive = each token depends on prior tokens (causal attention)."},
 {"type":"mcq","q":"A deterministic workflow is preferred over an autonomous agent when:",
  "opts":[("A","The path is dynamic and decided at runtime"),("B","Steps and ordering are known/fixed and you need reliability/auditability"),("C","You want maximum unpredictability"),("D","No tools are involved ever")],"ans":"B",
  "exp":"Fixed, known sequences favor deterministic workflows."},
])

M2 = ("Data Preparation", 14, [
 {"type":"mcq","q":"Chunk overlap exists primarily to:",
  "opts":[("A","Reduce cost"),("B","Preserve context across chunk boundaries"),("C","Shuffle data"),("D","Increase hallucination")],"ans":"B",
  "exp":"Overlap keeps boundary-spanning ideas retrievable."},
 {"type":"mcq","q":"A typical reasonable overlap is around:",
  "opts":[("A","0%"),("B","10-20%"),("C","60%"),("D","100%")],"ans":"B",
  "exp":"~10-20% balances continuity against bloat."},
 {"type":"mcq","q":"The core chunk-size trade-off is:",
  "opts":[("A","Large = precise, small = contextual"),("B","Large = more context but diluted focus; small = precise but fragmented"),("C","Size never matters"),("D","Bigger is always better")],"ans":"B",
  "exp":"Large chunks add context but dilute; small chunks are precise but fragment ideas."},
 {"type":"mcq","q":"Structure-aware (recursive) chunking respects:",
  "opts":[("A","Random cut points"),("B","Natural boundaries like headings, paragraphs, code blocks"),("C","Only character counts"),("D","Embedding dimensions")],"ans":"B",
  "exp":"It splits on semantic/structural boundaries."},
 {"type":"mcq","q":"For a FAQ where answers are short and self-contained, best chunking is:",
  "opts":[("A","One Q&A pair per chunk"),("B","Whole KB as one chunk"),("C","20-char splits"),("D","4000-token chunks")],"ans":"A",
  "exp":"Atomic Q&A pairs maximize precision."},
 {"type":"mcq","q":"Embedding model context length matters MOST for:",
  "opts":[("A","Short tweets"),("B","Long-document chunks (truncation risk)"),("C","Query side only"),("D","Never")],"ans":"B",
  "exp":"Long chunks can exceed the embedder's max length and be truncated."},
 {"type":"mcq","q":"Query and index embeddings must come from:",
  "opts":[("A","Any two models"),("B","The same embedding model/version"),("C","Different models for diversity"),("D","A random model")],"ans":"B",
  "exp":"Vectors are only comparable within the same model's space."},
 {"type":"mcq","q":"Switching the embedding model after indexing requires:",
  "opts":[("A","Nothing"),("B","Re-embedding the corpus and rebuilding/refreshing the index"),("C","Only changing temperature"),("D","Deleting metadata")],"ans":"B",
  "exp":"New model = new vector space; you must re-embed."},
 {"type":"mcq","q":"A Delta Sync vector index stays current by:",
  "opts":[("A","Manual nightly full re-embeds"),("B","Incrementally syncing from the source Delta table (via CDF)"),("C","Reloading a CSV"),("D","Disabling the index")],"ans":"B",
  "exp":"Delta Sync incrementally updates from the source table."},
 {"type":"mcq","q":"Storing an access-tier field for filtering should be done as:",
  "opts":[("A","Buried in chunk text"),("B","Metadata on each record used as a query-time filter"),("C","In model weights"),("D","Discarded")],"ans":"B",
  "exp":"Metadata enables filtering and access control."},
 {"type":"mcq","q":"Hybrid search adds a lexical/keyword component mainly to:",
  "opts":[("A","Lower cost"),("B","Match exact terms, IDs, and rare tokens dense vectors blur"),("C","Auto-chunk"),("D","Fine-tune")],"ans":"B",
  "exp":"Keyword matching catches exact strings/rare tokens."},
 {"type":"mcq","q":"A reranker after retrieval is used to:",
  "opts":[("A","Embed documents"),("B","Re-score candidates so the most relevant enter the top-k sent to the LLM"),("C","Serve the endpoint"),("D","Mask PII")],"ans":"B",
  "exp":"Rerankers refine ordering of retrieved candidates."},
 {"type":"mcq","q":"Cleaning boilerplate (nav/ads/footers) before chunking improves:",
  "opts":[("A","Retrieval precision"),("B","GPU temperature"),("C","Token price of the LLM"),("D","Embedding dimension")],"ans":"A",
  "exp":"Removing junk prevents noisy embeddings, improving precision."},
 {"type":"mcq","q":"Scanned-image PDFs need which extra step before chunking?",
  "opts":[("A","OCR to create a text layer"),("B","Higher temperature"),("C","Bigger k"),("D","No step")],"ans":"A",
  "exp":"Scanned images have no text layer; OCR is required."},
 {"type":"mcq","q":"The Python package best suited to parse many doc types into clean RAG elements is:",
  "opts":[("A","requests"),("B","unstructured"),("C","pillow"),("D","beautifulsoup (HTML only)")],"ans":"B",
  "exp":"`unstructured` parses many formats into clean elements."},
 {"type":"mcq","q":"Near-duplicate documents inflate retrieval. Best data-prep fix:",
  "opts":[("A","Add more duplicates"),("B","Deduplicate/cluster near-identical content before indexing"),("C","Disable metadata"),("D","Increase temperature")],"ans":"B",
  "exp":"Dedup improves diversity and precision."},
 {"type":"mcq","q":"To support GDPR erasure, chunks should be stored with:",
  "opts":[("A","Randomized IDs each run"),("B","Stable source_id/chunk_id keys in a CDF-enabled Delta table"),("C","One giant blob"),("D","No source mapping")],"ans":"B",
  "exp":"Stable IDs + CDF enable targeted deletion that propagates to the index."},
 {"type":"mcq","q":"Page numbers/section headings should be preserved as metadata to support:",
  "opts":[("A","Citations/traceability"),("B","Lower latency"),("C","Higher temperature"),("D","Smaller embeddings")],"ans":"A",
  "exp":"Positional metadata enables accurate citations."},
 {"type":"mcq","q":"Cosine vs L2 vs dot product: a production index must be queried with:",
  "opts":[("A","Any metric"),("B","The metric it was built for"),("C","Always L2"),("D","Always dot")],"ans":"B",
  "exp":"Querying with a mismatched metric yields wrong rankings."},
 {"type":"mcq","q":"Why keep original text alongside normalized text?",
  "opts":[("A","To embed twice"),("B","To ground/cite on faithful original wording while embedding on normalized text"),("C","To increase cost"),("D","No reason")],"ans":"B",
  "exp":"Citations should match the source verbatim; embed on normalized text."},
 {"type":"mcq","q":"Excessive overlap (e.g., 60%) most likely causes:",
  "opts":[("A","A smaller index"),("B","Index bloat and redundant near-duplicate hits crowding top-k"),("C","Lower cost"),("D","Better diversity")],"ans":"B",
  "exp":"Too much overlap inflates the index and fills top-k with duplicates."},
 {"type":"mcq","q":"Over-length chunks fed to an embedder are:",
  "opts":[("A","Rejected entirely"),("B","Silently truncated to the max sequence length, losing tail content"),("C","Auto-split safely"),("D","Embedded perfectly")],"ans":"B",
  "exp":"Inputs beyond max length are truncated, losing information."},
 {"type":"mcq","q":"Aggressive lowercasing can HURT retrieval for:",
  "opts":[("A","Code/identifiers/chemical formulas where case matters"),("B","All corpora equally"),("C","Nothing"),("D","Only short text")],"ans":"A",
  "exp":"Case can be semantically significant; normalize corpus-aware."},
 {"type":"mcq","q":"With only ~2% of rows changing daily, the cost-smart embedding strategy is:",
  "opts":[("A","Full nightly re-embed"),("B","Incremental embedding of changed/new rows via CDF/Delta Sync"),("C","Tiny embedder for all"),("D","Stop indexing")],"ans":"B",
  "exp":"Incremental embedding avoids wasteful full re-embeds."},
 {"type":"mcq","q":"A Delta table is preferred over raw files for RAG sources because it provides:",
  "opts":[("A","ACID, versioning/time-travel, schema, and CDF for incremental sync"),("B","Faster GPUs"),("C","Lower temperature"),("D","Bigger embeddings")],"ans":"A",
  "exp":"Delta offers governance/versioning and CDF for sync."},
 {"type":"mcq","q":"High recall but low precision (many irrelevant chunks) is best improved by:",
  "opts":[("A","Reranking + tighter metadata filters + lower k"),("B","Higher k"),("C","Removing metadata"),("D","Whole-doc chunks")],"ans":"A",
  "exp":"Reranking/filtering and smaller k raise precision."},
 {"type":"mcq","q":"For exact part-number lookups plus semantic questions, implement:",
  "opts":[("A","Dense-only retrieval"),("B","Hybrid (dense + lexical) and/or exact-match metadata filtering"),("C","Keyword-only"),("D","Larger chunks")],"ans":"B",
  "exp":"Hybrid covers exact tokens and semantics."},
 {"type":"mcq","q":"PII in support tickets must be handled before embedding by:",
  "opts":[("A","Embedding as-is"),("B","Detecting and masking/redacting it"),("C","Increasing chunk size"),("D","Lowering temperature")],"ans":"B",
  "exp":"Detect and mask PII before it enters embeddings/logs."},
 {"type":"mcq","q":"Document-level metadata (author, doc_type) is typically:",
  "opts":[("A","Discarded"),("B","Copied onto each chunk for filtering"),("C","Stored only in weights"),("D","Randomized")],"ans":"B",
  "exp":"Doc-level metadata is propagated to chunks for filtering."},
 {"type":"mcq","q":"Fixed-token chunking of source code is harmful because:",
  "opts":[("A","It keeps functions whole"),("B","It can split functions/classes mid-body into uncompilable fragments"),("C","It improves syntax"),("D","It adds metadata")],"ans":"B",
  "exp":"Fixed cuts break syntactic units; use AST/structure-aware chunking."},
 {"type":"mcq","q":"Outdated policy versions being cited is best fixed by:",
  "opts":[("A","Indexing both with no metadata"),("B","Effective-date metadata + recency filtering/boosting + superseding old versions"),("C","More overlap"),("D","Higher k")],"ans":"B",
  "exp":"Encode recency in metadata and filter/supersede."},
 {"type":"mcq","q":"Context Recall measures:",
  "opts":[("A","Fraction of retrieved chunks that are relevant"),("B","Fraction of relevant info that was successfully retrieved"),("C","Answer fluency"),("D","Latency")],"ans":"B",
  "exp":"Recall = coverage of the relevant information."},
 {"type":"mcq","q":"Context Precision measures:",
  "opts":[("A","Coverage of relevant info"),("B","Signal-to-noise: fraction of retrieved chunks that are relevant"),("C","Generation speed"),("D","Token cost")],"ans":"B",
  "exp":"Precision = relevance of what was retrieved."},
 {"type":"mcq","q":"Too-small chunks tend to harm:",
  "opts":[("A","Context Recall (fragmented ideas missed within top-k)"),("B","Latency only"),("C","Nothing"),("D","Embedding dimension")],"ans":"A",
  "exp":"Fragmentation spreads an idea across many tiny chunks, hurting recall."},
 {"type":"mcq","q":"A mixed corpus (HTML/PDF/MD) for one index should converge to:",
  "opts":[("A","Different embedders per type"),("B","Clean normalized text + consistent metadata + one shared embedder"),("C","Raw bytes"),("D","Random chunking")],"ans":"B",
  "exp":"Normalize and unify before a single shared embedder/index."},
 {"type":"mcq","q":"Metadata filtering solves what semantic similarity cannot:",
  "opts":[("A","Hard constraints (date, type, tenant, access)"),("B","Fluency"),("C","Token cost"),("D","GPU scheduling")],"ans":"A",
  "exp":"Filtering enforces exact attribute constraints."},
 {"type":"mcq","q":"A smaller/faster embedder may be chosen despite lower benchmark scores because:",
  "opts":[("A","It runs on every doc and query — lower latency/cost at scale, often negligible quality loss for short chunks"),("B","It increases cost"),("C","It changes the metric"),("D","It removes metadata")],"ans":"A",
  "exp":"Embedding cost/latency at scale can outweigh small quality gains."},
 {"type":"mcq","q":"Storing a stable chunk_id supports all EXCEPT:",
  "opts":[("A","Citations"),("B","Targeted updates/deletes"),("C","Deduplication"),("D","Increasing temperature")],"ans":"D",
  "exp":"chunk_id aids citation/update/dedup, not decoding temperature."},
 {"type":"mcq","q":"Which metric pair judges RETRIEVAL (not generation)?",
  "opts":[("A","Context Precision & Context Recall"),("B","BLEU & ROUGE"),("C","Latency & QPS"),("D","Perplexity & BLEU")],"ans":"A",
  "exp":"Precision/recall judge retrieval; BLEU/ROUGE judge generation."},
 {"type":"mcq","q":"For long legal docs, the key embedding-model selection factor is:",
  "opts":[("A","Training framework"),("B","Max sequence (context) length"),("C","License color"),("D","GPU count")],"ans":"B",
  "exp":"Context length must accommodate long chunks to avoid truncation."},
 {"type":"open","q":"Explain why a Delta Sync index can show correct row counts yet return stale vectors after a model upgrade, and the fix.",
  "opts":None,"ans":"See explanation",
  "exp":"Sync propagates rows/text but not a new embedding space; existing vectors remain from the old model. You must re-embed the corpus with the new model and rebuild/refresh the index."},
 {"type":"open","q":"Describe the distinct preprocessing risk of HTML, native PDF, and scanned-image documents for RAG.",
  "opts":None,"ans":"See explanation",
  "exp":"HTML: boilerplate noise (strip it). Native PDF: broken reading order/columns and tables (layout-aware parsing, preserve structure). Scanned image: no text layer (run OCR, validate quality). All converge to clean normalized text + consistent metadata."},
 {"type":"open","q":"Why store BOTH original and normalized chunk text? Tie it to citation faithfulness.",
  "opts":None,"ans":"See explanation",
  "exp":"You embed on normalized text for consistent retrieval but ground/cite on the original so quotes match the source verbatim and remain auditable; feeding only normalized text could make citations diverge from the source."},
 {"type":"mcq","q":"A 700-token chunk with a 512-token embedder is best handled by:",
  "opts":[("A","Ignoring it"),("B","Sub-splitting to fit (with overlap) or using a longer-context embedder"),("C","Raising temperature"),("D","Switching the generator")],"ans":"B",
  "exp":"Fit chunks to the embedder's limit or pick a longer-context model."},
 {"type":"mcq","q":"The main purpose of metadata in a vector record is to enable:",
  "opts":[("A","Filtering, access control, and citations"),("B","Faster GPUs"),("C","Lower temperature"),("D","Token savings in generation")],"ans":"A",
  "exp":"Metadata drives filtering, ACLs, and citation."},
 {"type":"mcq","q":"Which is TRUE about dot product vs cosine for non-normalized vectors?",
  "opts":[("A","They are identical"),("B","They can differ; cosine normalizes magnitude, dot does not"),("C","Cosine ignores direction"),("D","Dot ignores all vectors")],"ans":"B",
  "exp":"For non-normalized vectors, dot ≠ cosine."},
 {"type":"mcq","q":"Recency-sensitive corpora typically need:",
  "opts":[("A","Date metadata + filtering/boosting"),("B","Bigger embeddings"),("C","Higher temperature"),("D","No metadata")],"ans":"A",
  "exp":"Date metadata lets you prefer current content."},
 {"type":"mcq","q":"Which step most directly improves precision on a noisy web-scraped corpus?",
  "opts":[("A","Cleaning boilerplate before chunking"),("B","Higher k"),("C","Removing metadata"),("D","Lower LLM temperature")],"ans":"A",
  "exp":"Cleaning reduces junk in embeddings, improving precision."},
 {"type":"mcq","q":"Hybrid search improves recall on precise terms by adding:",
  "opts":[("A","A lexical/keyword match alongside dense vectors"),("B","More overlap"),("C","Bigger chunks"),("D","Higher temperature")],"ans":"A",
  "exp":"Lexical matching catches exact/rare terms."},
 {"type":"mcq","q":"Which is the best chunking strategy for a corpus of legal contracts with clearly numbered clauses?",
  "opts":[("A","Fixed 1000-char cuts ignoring structure"),("B","Clause/section-aware chunking with clause-number metadata"),("C","One chunk per whole contract"),("D","Random splits")],"ans":"B",
  "exp":"Clause-aware chunking keeps legal units intact and enables precise citation by clause."},
])

M3 = ("Application Development", 30, [
 {"type":"mcq","q":"The SQL function to call an LLM/served model for batch scoring is:",
  "opts":[("A","ai_query()"),("B","explode()"),("C","collect_set()"),("D","pivot()")],"ans":"A",
  "exp":"ai_query() invokes a served endpoint from SQL."},
 {"type":"mcq","q":"In 2026, AI Gateway and ai_query batch: which is true?",
  "opts":[("A","Gateway rate-limits ai_query batch"),("B","Gateway only usage-TRACKS ai_query; it does not rate-limit it"),("C","ai_query bypasses UC"),("D","ai_query cannot be governed")],"ans":"B",
  "exp":"AI Gateway tracks usage for ai_query but does not rate-limit batch."},
 {"type":"mcq","q":"To package a custom chain with bespoke pre/post-processing as one deployable model, use:",
  "opts":[("A","A pickle file"),("B","A custom MLflow PyFunc model"),("C","A text file"),("D","A Delta table")],"ans":"B",
  "exp":"PyFunc wraps arbitrary Python into a servable model."},
 {"type":"mcq","q":"A model signature defines:",
  "opts":[("A","GPU type"),("B","Expected input/output schema for validation"),("C","Embeddings"),("D","Encryption keys")],"ans":"B",
  "exp":"Signatures declare I/O schema for serving validation."},
 {"type":"mcq","q":"An MLflow 'input example' helps by:",
  "opts":[("A","Encrypting weights"),("B","Letting MLflow infer/validate the signature and document request format"),("C","Setting temperature"),("D","Creating embeddings")],"ans":"B",
  "exp":"Input examples support signature inference and testing."},
 {"type":"mcq","q":"Pay-per-token Foundation Model APIs are best for:",
  "opts":[("A","Steady high QPS with strict SLA"),("B","Spiky/low/unpredictable volume"),("C","Reserved capacity needs"),("D","Guaranteed throughput")],"ans":"B",
  "exp":"Pay-per-token suits variable/low volume with no reserved capacity."},
 {"type":"mcq","q":"Provisioned throughput is best for:",
  "opts":[("A","Sporadic testing"),("B","Steady high volume needing predictable latency/throughput"),("C","One-off demos"),("D","Nightly batch only")],"ans":"B",
  "exp":"Provisioned throughput reserves capacity for steady high volume."},
 {"type":"mcq","q":"Function/tool calling lets the model:",
  "opts":[("A","Quantize itself"),("B","Emit a structured call (name+args) your app executes"),("C","Tokenize input"),("D","Distill weights")],"ans":"B",
  "exp":"Tool calling produces a structured invocation."},
 {"type":"mcq","q":"Temperature controls:",
  "opts":[("A","Retrieval k"),("B","Output randomness/creativity"),("C","Embedding dimension"),("D","Chunk overlap")],"ans":"B",
  "exp":"Temperature scales the token distribution's randomness."},
 {"type":"mcq","q":"For deterministic regression tests, set:",
  "opts":[("A","temperature=0 (greedy)"),("B","temperature=2"),("C","top_p=1, temperature=2"),("D","random sampling")],"ans":"A",
  "exp":"temperature=0 maximizes determinism."},
 {"type":"mcq","q":"An Output Parser in a chain:",
  "opts":[("A","Fetches documents"),("B","Converts raw text into a validated structured object"),("C","Encrypts prompts"),("D","Schedules jobs")],"ans":"B",
  "exp":"Parsers structure/validate model output."},
 {"type":"mcq","q":"Windowed (buffer) memory provides:",
  "opts":[("A","Per-message fine-tuning"),("B","Short-term recall by injecting recent turns"),("C","Bigger embeddings"),("D","No memory")],"ans":"B",
  "exp":"Buffer memory injects recent turns as context."},
 {"type":"mcq","q":"To give an LLM proprietary, frequently-updated data without retraining, use:",
  "opts":[("A","Weekly fine-tuning"),("B","RAG over a synced index"),("C","Static system-prompt facts"),("D","Lower temperature")],"ans":"B",
  "exp":"RAG retrieves current data at query time."},
 {"type":"mcq","q":"The MLflow Prompt Registry primarily enables:",
  "opts":[("A","Versioned, governed prompts with aliases for promote/rollback"),("B","GPU scheduling"),("C","Embedding training"),("D","Token compression")],"ans":"A",
  "exp":"It version-controls prompts with aliases/lifecycle."},
 {"type":"mcq","q":"MCP (Model Context Protocol) is:",
  "opts":[("A","A decoding parameter"),("B","An open standard for connecting agents to tools/data"),("C","An embedding model"),("D","A chunking method")],"ans":"B",
  "exp":"MCP standardizes agent↔tool/data connectivity."},
 {"type":"mcq","q":"On Databricks, Managed OAuth MCP Connectors let you:",
  "opts":[("A","Train embeddings"),("B","Connect external services (GitHub, Drive, SharePoint) as governed tools without managing credentials"),("C","Lower latency"),("D","Disable UC")],"ans":"B",
  "exp":"Managed OAuth connectors govern external tool access."},
 {"type":"mcq","q":"Which is NOT a valid guardrail technique?",
  "opts":[("A","Content/safety filters on I/O"),("B","Topic/scope classifiers"),("C","System-prompt constraints"),("D","Raising temperature for variety")],"ans":"D",
  "exp":"Higher temperature worsens safety; it isn't a guardrail."},
 {"type":"mcq","q":"To reduce hallucination in a RAG chain, the most effective instruction is:",
  "opts":[("A","'Be creative'"),("B","'Answer only from context; if absent, say you don't know'"),("C","'Use many tokens'"),("D","'Ignore the context'")],"ans":"B",
  "exp":"Constraining to context and licensing 'I don't know' curbs fabrication."},
 {"type":"mcq","q":"A reranker is added to a chain to:",
  "opts":[("A","Embed docs"),("B","Promote the most relevant chunks into the top-k sent to the LLM"),("C","Serve the model"),("D","Mask PII")],"ans":"B",
  "exp":"Rerankers refine which context reaches the generator."},
 {"type":"mcq","q":"Higher k can DECREASE quality because:",
  "opts":[("A","It always improves recall with no cost"),("B","Added noise and token pressure can distract the generator and truncate the budget"),("C","It lowers latency"),("D","It removes metadata")],"ans":"B",
  "exp":"Beyond optimal k, noise/token pressure hurt generation."},
 {"type":"mcq","q":"To use the OpenAI SDK against a Databricks OpenAI-compatible endpoint, you must:",
  "opts":[("A","Convert to GGUF"),("B","Set base_url to the endpoint and use a Databricks token as api_key"),("C","Set OPENAI_ORG only"),("D","Do nothing")],"ans":"B",
  "exp":"Point base_url at the endpoint and authenticate with a Databricks token."},
 {"type":"mcq","q":"max_output_tokens set too high in a long-context RAG prompt can:",
  "opts":[("A","Always be safe"),("B","Exceed the total context window (input+output) and error/truncate"),("C","Reduce cost"),("D","Improve recall")],"ans":"B",
  "exp":"Input + output must fit the window; over-reserving output can overflow it."},
 {"type":"mcq","q":"A streaming chat UI needs:",
  "opts":[("A","Token streaming from the endpoint"),("B","Batch inference"),("C","Delta time travel"),("D","Photon")],"ans":"A",
  "exp":"Streaming emits tokens incrementally."},
 {"type":"mcq","q":"To let an agent safely query a governed table as a tool, use:",
  "opts":[("A","A Unity Catalog function exposed as a tool"),("B","Hard-coded creds in the prompt"),("C","A public CSV link"),("D","Disabled permissions")],"ans":"A",
  "exp":"UC functions keep permissions/lineage intact."},
 {"type":"mcq","q":"An agent stuck retrying a failing tool is best bounded by:",
  "opts":[("A","Infinite retries"),("B","A max-iteration/step limit plus adaptive error handling"),("C","Higher temperature"),("D","Removing observations")],"ans":"B",
  "exp":"Step limits bound loops; adaptive handling changes strategy."},
 {"type":"mcq","q":"Built-in LangChain-flavor logging is appropriate when:",
  "opts":[("A","The app is a recognized serializable LangChain object"),("B","You have arbitrary custom Python orchestration"),("C","No model is involved"),("D","You only need a CSV")],"ans":"A",
  "exp":"Use the flavor for known LangChain objects; PyFunc for bespoke logic."},
 {"type":"mcq","q":"Comparing two prompt versions fairly requires:",
  "opts":[("A","Different datasets per version"),("B","The same fixed dataset and scorers, logging the version"),("C","Eyeballing five outputs"),("D","Unmatched production traffic")],"ans":"B",
  "exp":"Hold data/scorers constant; track the version."},
 {"type":"mcq","q":"Semantic caching helps a FAQ bot with many paraphrases because:",
  "opts":[("A","Exact-string cache catches paraphrases"),("B","It matches by embedding similarity, reusing answers across paraphrases (with TTL/invalidation)"),("C","It disables retrieval"),("D","It raises k")],"ans":"B",
  "exp":"Semantic cache matches paraphrased queries by similarity."},
 {"type":"mcq","q":"A chain fails on serving with a missing-dependency error but works locally because:",
  "opts":[("A","The model is too accurate"),("B","The logged model's recorded environment lacks a lib the local env had"),("C","UC blocks serving"),("D","Signatures block serving")],"ans":"B",
  "exp":"Serving rebuilds from recorded deps; capture them accurately."},
 {"type":"mcq","q":"Structured (typed) tool output reduces hallucination by:",
  "opts":[("A","Removing the LLM"),("B","Giving precise, parseable grounding the model is less likely to misread"),("C","Raising temperature"),("D","Disabling retrieval")],"ans":"B",
  "exp":"Typed results are unambiguous to ground on."},
 {"type":"mcq","q":"An embedding endpoint vs a chat endpoint: the embedding endpoint:",
  "opts":[("A","Generates the final answer"),("B","Converts text to vectors for retrieval"),("C","Serves the UI"),("D","Stores secrets")],"ans":"B",
  "exp":"Embedding endpoints produce vectors; chat endpoints generate."},
 {"type":"mcq","q":"To keep a chain model-agnostic across dev/prod, you should:",
  "opts":[("A","Hard-code the model name"),("B","Parameterize the model/endpoint via config or alias injected at runtime"),("C","Duplicate the codebase"),("D","Recompile per model")],"ans":"B",
  "exp":"Externalize the model reference to swap without code change."},
 {"type":"mcq","q":"A query needing both DB facts and document context is best served by:",
  "opts":[("A","A static prompt"),("B","A tool-using agent (UC function for DB + retriever for docs) that synthesizes"),("C","Keyword-only search"),("D","Lower temperature")],"ans":"B",
  "exp":"Combine a DB tool and a retriever, then synthesize."},
 {"type":"mcq","q":"Mis-attribution of facts to the wrong document despite good faithfulness suggests:",
  "opts":[("A","Temperature too high"),("B","Context lacks per-chunk delimiters/source tags for attribution"),("C","k too low"),("D","Embedding too small")],"ans":"B",
  "exp":"Delimit and tag each chunk's source so the model can attribute."},
 {"type":"mcq","q":"A comparison question ('what changed between v3 and v4') retrieving only one version is fixed by:",
  "opts":[("A","Higher temperature"),("B","Query decomposition/multi-query with per-version metadata filters, then synthesize"),("C","One huge chunk"),("D","k=1")],"ans":"B",
  "exp":"Decompose into per-version sub-queries and synthesize the diff."},
 {"type":"mcq","q":"Schema-valid JSON with hallucinated values is best addressed by:",
  "opts":[("A","Trusting the parser"),("B","Parser for shape PLUS grounding + a faithfulness/correctness check"),("C","Higher temperature"),("D","Removing the schema")],"ans":"B",
  "exp":"Validity ≠ truth; add grounding and faithfulness checks."},
 {"type":"mcq","q":"Letting an agent web-search but ignore injected instructions in pages requires:",
  "opts":[("A","Treating retrieved content as untrusted data, delimiting it, and not letting tool output trigger privileged actions"),("B","Trusting all pages"),("C","Higher temperature"),("D","Removing guardrails")],"ans":"A",
  "exp":"Retrieved content is data, not commands; restrict privileged actions."},
 {"type":"mcq","q":"A serving 401 in a job but not the notebook usually means:",
  "opts":[("A","The model is too big"),("B","The job's principal lacks endpoint permission or uses an expired/wrong token"),("C","Temperature drift"),("D","Chunk size")],"ans":"B",
  "exp":"Grant the service principal access and use managed secrets, not personal tokens."},
 {"type":"mcq","q":"Unconditional sequential tool calls inflating p99 latency are best fixed by:",
  "opts":[("A","Adding more tools"),("B","Conditional tool use + parallelizing independent calls"),("C","Higher temperature"),("D","More output tokens")],"ans":"B",
  "exp":"Call tools only when needed and parallelize independent ones."},
 {"type":"mcq","q":"top_p (nucleus sampling) and temperature both control:",
  "opts":[("A","Retrieval k"),("B","Output randomness; commonly tune one"),("C","Embedding size"),("D","Governance")],"ans":"B",
  "exp":"Both shape randomness; lower = more deterministic."},
 {"type":"mcq","q":"Prompt aliases enable zero-code-change rollback only if the app:",
  "opts":[("A","Hard-codes the prompt text"),("B","Resolves the prompt by alias at runtime"),("C","Pins a fixed version"),("D","Ignores the registry")],"ans":"B",
  "exp":"Code must reference the alias so repointing it changes behavior."},
 {"type":"mcq","q":"A signature validation failure at serving means:",
  "opts":[("A","GPU overheating"),("B","The request schema doesn't match the declared signature"),("C","Embedding too small"),("D","Prompt too creative")],"ans":"B",
  "exp":"It's a pre-inference I/O contract mismatch."},
 {"type":"mcq","q":"Which MLflow capability lets the same scorers run in dev and prod?",
  "opts":[("A","MLflow 3 evaluation/monitoring"),("B","Photon"),("C","Time travel"),("D","A second metrics codebase")],"ans":"A",
  "exp":"MLflow 3 unifies eval/monitoring with shared scorers."},
 {"type":"open","q":"Explain how token streaming, MLflow Tracing, and inference tables coexist for one deployed agent.",
  "opts":None,"ans":"See explanation",
  "exp":"Streaming returns tokens incrementally (transport); Tracing emits structured spans (observability); inference tables persist payloads and can store the traces. The same request is streamed, traced, and logged — three independent layers."},
 {"type":"open","q":"Why is 'just fine-tune on our docs' usually the wrong first answer to doc-Q&A hallucination? Order the cheaper steps.",
  "opts":None,"ans":"See explanation",
  "exp":"Hallucination is usually a grounding gap, not a capability gap. Cheaper first: (1) grounding context + 'say I don't know'; (2) improve RAG/retrieval (chunking, reranking, k); (3) citations + faithfulness check. Fine-tuning is costly, slow, goes stale, and risks new errors; reserve it for style/behavior."},
 {"type":"open","q":"List the most common gaps that make an agent pass in AI Playground but fail in production.",
  "opts":None,"ans":"See explanation",
  "exp":"Identity/permissions (prod service principal lacks grants); environment/dependencies (serving rebuilds from recorded deps); messier/adversarial inputs (evaluate on representative golden set, add guardrails); scale/latency (cold starts, rate limits); observability (enable tracing + inference tables pre-launch)."},
 {"type":"mcq","q":"Which is the correct reason to wrap a multi-component app as one MLflow model?",
  "opts":[("A","Atomic versioning + one signed endpoint + unified tracing/governance"),("B","To slow it down"),("C","To avoid Unity Catalog"),("D","To remove signatures")],"ans":"A",
  "exp":"One artifact gives atomic deploy/rollback, one contract, and observability."},
 {"type":"mcq","q":"A chain occasionally returns malformed JSON. Best dev-time mitigation:",
  "opts":[("A","Ignore failures"),("B","Structured parser with retry/repair on parse error"),("C","Raise temperature"),("D","Drop the schema")],"ans":"B",
  "exp":"A parser that re-asks/repairs makes output robust."},
 {"type":"mcq","q":"Which is TRUE about provisioned-throughput endpoints for development?",
  "opts":[("A","They can't be logged with MLflow"),("B","They reserve dedicated capacity for steady workloads and are still MLflow-trackable"),("C","They require no endpoint"),("D","They are always cheaper than pay-per-token")],"ans":"B",
  "exp":"They reserve capacity for steady volume; models using them remain trackable; not always cheaper (idle cost)."},
 {"type":"mcq","q":"A 'router' chain that picks billing vs technical vs sales models implements:",
  "opts":[("A","A static prompt"),("B","Intent classification + dispatch to a specialized chain/model"),("C","Quantization"),("D","Embedding training")],"ans":"B",
  "exp":"A routing layer classifies intent and forwards to the right specialist."},
])
