# -*- coding: utf-8 -*-
"""Module Drills part B — Modules 4-6 (50 each)."""

M4 = ("Assembling & Deploying Applications", 22, [
 {"type":"mcq","q":"After logging a model, the native deployment path is:",
  "opts":[("A","Pickle → DBFS → manual server"),("B","Register to Unity Catalog → create a Model Serving endpoint"),("C","Email the artifact"),("D","Run a manual Docker container")],"ans":"B",
  "exp":"MLflow → UC registration → Model Serving is the governed path."},
 {"type":"mcq","q":"The Unity Catalog model namespace has the form:",
  "opts":[("A","model"),("B","schema.model"),("C","catalog.schema.model"),("D","workspace/model")],"ans":"C",
  "exp":"UC uses a three-level namespace: catalog.schema.model."},
 {"type":"mcq","q":"Scale-to-zero means:",
  "opts":[("A","The model is deleted"),("B","Compute scales to zero when idle and cold-starts on next request"),("C","Tokens capped at zero"),("D","Logging disabled")],"ans":"B",
  "exp":"Idle compute is released; the next request triggers a cold start."},
 {"type":"mcq","q":"A canary rollout (10% to a new version) uses:",
  "opts":[("A","Deleting the old version"),("B","Traffic splitting across served entities on one endpoint"),("C","Time travel"),("D","A notebook comment")],"ans":"B",
  "exp":"Traffic splitting routes a fraction to the new served entity."},
 {"type":"mcq","q":"A stable client reference that survives version swaps is provided by:",
  "opts":[("A","A UC model alias"),("B","A pickle path"),("C","A random URL"),("D","A screenshot")],"ans":"A",
  "exp":"Aliases (e.g., @prod) point to a version and can be repointed."},
 {"type":"mcq","q":"Zero-code rollback is achieved by:",
  "opts":[("A","Deleting v2 manually"),("B","Repointing the alias / traffic split to the last good version"),("C","Renaming files"),("D","Recompiling")],"ans":"B",
  "exp":"Repoint the alias/traffic to the prior version; artifacts are preserved."},
 {"type":"mcq","q":"AI Gateway sits in front of endpoints to provide all EXCEPT:",
  "opts":[("A","Rate limiting"),("B","Usage/cost tracking"),("C","Inference-table logging and guardrails"),("D","Training the model")],"ans":"D",
  "exp":"AI Gateway governs runtime; it doesn't train models."},
 {"type":"mcq","q":"Inference tables capture:",
  "opts":[("A","Aggregate token cost only"),("B","Request/response payloads, latency, traces, identity, guardrail outcomes"),("C","GPU serial numbers"),("D","Source code")],"ans":"B",
  "exp":"Inference tables log endpoint traffic content to a UC Delta table."},
 {"type":"mcq","q":"Per-team cost chargeback comes from:",
  "opts":[("A","system.serving.endpoint_usage joined with served_entities"),("B","The model signature"),("C","MLflow traces alone"),("D","The prompt")],"ans":"A",
  "exp":"Usage/system tables provide token/cost accounting."},
 {"type":"mcq","q":"The default inference-table name pattern is:",
  "opts":[("A","<catalog>.<schema>.<endpoint>_payload"),("B","payload.csv"),("C","model.json"),("D","root/logs")],"ans":"A",
  "exp":"AI Gateway creates <catalog>.<schema>.<endpoint>_payload."},
 {"type":"mcq","q":"Legacy inference tables, in 2026:",
  "opts":[("A","Are the recommended choice"),("B","Are deprecated (unsupported after Apr 30 2026); migrate to AI Gateway-enabled tables"),("C","Never existed"),("D","Cannot be migrated")],"ans":"B",
  "exp":"Migrate legacy tables to AI Gateway-enabled inference tables."},
 {"type":"mcq","q":"The max logged payload/trace size for inference tables is:",
  "opts":[("A","1 KiB"),("B","1 MiB"),("C","1 GiB"),("D","Unlimited")],"ans":"B",
  "exp":"Payloads over ~1 MiB are logged as null with an error code."},
 {"type":"mcq","q":"A 429 error from an endpoint indicates:",
  "opts":[("A","Success"),("B","Rate limiting/throttling"),("C","The model is too small"),("D","A DNS failure")],"ans":"B",
  "exp":"429 = too many requests; add backoff/quota/provisioned capacity."},
 {"type":"mcq","q":"Inference logs are NOT guaranteed to be recorded when:",
  "opts":[("A","Requests succeed"),("B","The endpoint returns certain errors (e.g., 401/403/429/500)"),("C","Latency is low"),("D","Unity Catalog is on")],"ans":"B",
  "exp":"Logs may be skipped for some error responses."},
 {"type":"mcq","q":"Provider fallback (route to backup on outage/degradation) with unified logging is provided by:",
  "opts":[("A","AI Gateway"),("B","Delta Live Tables"),("C","A Volume"),("D","A widget")],"ans":"A",
  "exp":"AI Gateway handles routing/fallback and logging."},
 {"type":"mcq","q":"A bursty, unpredictable customer feature should use:",
  "opts":[("A","Large reserved provisioned throughput"),("B","Pay-per-token or scale-to-zero serving"),("C","An always-on GPU VM"),("D","Batch-only")],"ans":"B",
  "exp":"Spiky traffic favors pay-per-token/scale-to-zero to avoid idle cost."},
 {"type":"mcq","q":"An overprovisioned endpoint with low, spiky volume should switch to:",
  "opts":[("A","More provisioned units"),("B","Pay-per-token (or scale-to-zero)"),("C","Disabling inference tables"),("D","Higher max tokens")],"ans":"B",
  "exp":"Low/spiky volume doesn't justify reserved capacity."},
 {"type":"mcq","q":"Terrible p99 latency correlated with idle periods indicates:",
  "opts":[("A","Cold starts on scale-to-zero"),("B","Too few chunks"),("C","Temperature drift"),("D","Embedding size")],"ans":"A",
  "exp":"Cold starts spike p99 after idle; warm a replica or use provisioned throughput."},
 {"type":"mcq","q":"A CI/CD promotion gate should be:",
  "opts":[("A","A Slack vote"),("B","An automated mlflow.genai.evaluate step on a golden set, failing on regression"),("C","Model file size"),("D","Random approval")],"ans":"B",
  "exp":"Automated eval thresholds gate promotion objectively."},
 {"type":"mcq","q":"For a nightly 5M-row classification job with no latency SLA, use:",
  "opts":[("A","A hot real-time endpoint 24/7"),("B","Batch inference (ai_query/scheduled batch)"),("C","Manual per-row calls"),("D","A streaming UI")],"ans":"B",
  "exp":"Batch scoring avoids paying for an always-on endpoint."},
 {"type":"mcq","q":"External model endpoints let you:",
  "opts":[("A","Only run offline"),("B","Route to third-party providers under Databricks governance with managed keys"),("C","Bypass logging"),("D","Avoid rate limits forever")],"ans":"B",
  "exp":"They proxy third-party providers with centralized governance."},
 {"type":"mcq","q":"Secrets for an endpoint should be supplied via:",
  "opts":[("A","Databricks secret scopes"),("B","The system prompt"),("C","A Git commit"),("D","A URL query parameter")],"ans":"A",
  "exp":"Secret scopes inject credentials securely, out of code/logs."},
 {"type":"mcq","q":"A readiness/health check on an endpoint ensures:",
  "opts":[("A","The model is loaded/ready before traffic routes"),("B","Documents are embedded"),("C","Logs are deleted"),("D","Temperature is raised")],"ans":"A",
  "exp":"Health checks gate routing until the model is ready."},
 {"type":"mcq","q":"A logged model fails to serve though it works locally. Likely cause/fix:",
  "opts":[("A","Too accurate; lower accuracy"),("B","Missing recorded deps; re-log accurate pip/conda + input example, test in clean env"),("C","UC incompatible with serving"),("D","Signatures block serving")],"ans":"B",
  "exp":"Capture correct dependencies; serving rebuilds from them."},
 {"type":"mcq","q":"To deploy retrieval+prompt+LLM+rules+parsing as one rollback-able unit:",
  "opts":[("A","5 hand-wired microservices"),("B","One MLflow model (PyFunc/chain) registered to UC, served via one endpoint, referenced by alias"),("C","A zip emailed to ops"),("D","Separate notebook jobs")],"ans":"B",
  "exp":"One artifact gives atomic versioning and governed rollback."},
 {"type":"mcq","q":"AI Gateway config changes take roughly:",
  "opts":[("A","Instant"),("B","~20-40s (rate-limit changes up to ~60s)"),("C","24 hours"),("D","Require endpoint deletion")],"ans":"B",
  "exp":"Config applies in ~20-40s; rate limits up to ~60s."},
 {"type":"mcq","q":"Adding a 21st subagent to a Supervisor via SDK:",
  "opts":[("A","Silently replaces the oldest"),("B","Fails — max is 20; remove/restructure"),("C","Creates a second supervisor"),("D","Converts one to a tool")],"ans":"B",
  "exp":"The 20-agent cap is a hard limit."},
 {"type":"mcq","q":"Enabling inference tables BEFORE launch matters because:",
  "opts":[("A","They capture only future traffic; post-incident enabling leaves no record of the failing requests"),("B","They reduce model size"),("C","They encrypt prompts"),("D","They auto-train the model")],"ans":"A",
  "exp":"You can't analyze traffic that wasn't logged."},
 {"type":"mcq","q":"Unity Catalog over the legacy workspace registry gives:",
  "opts":[("A","Cross-workspace governance, fine-grained permissions, lineage, 3-level namespace"),("B","Faster GPUs"),("C","Lower temperature"),("D","Bigger embeddings")],"ans":"A",
  "exp":"UC provides governed, cross-workspace model management."},
 {"type":"mcq","q":"A true zero-downtime upgrade uses:",
  "opts":[("A","Delete-then-deploy"),("B","Add the new version as a served entity, canary with health checks, shift traffic, repoint alias on regression"),("C","Manual workspace switch"),("D","A bigger model")],"ans":"B",
  "exp":"Coexisting versions + health-gated traffic shifting = no downtime."},
 {"type":"mcq","q":"Per-user rate limiting on an endpoint while a nightly ai_query batch runs unthrottled is:",
  "opts":[("A","Impossible"),("B","Expected — gateway per-user limits cap interactive serving; ai_query batch isn't gateway-rate-limited"),("C","A bug"),("D","Because ai_query bypasses UC")],"ans":"B",
  "exp":"Interactive requests are capped; batch ai_query is only usage-tracked."},
 {"type":"mcq","q":"MLflow vs Model Serving: the correct relationship is:",
  "opts":[("A","They are identical"),("B","MLflow packages/tracks/registers; Model Serving hosts the registered model as an endpoint"),("C","Serving trains the model"),("D","MLflow replaces UC")],"ans":"B",
  "exp":"MLflow handles lifecycle; serving hosts the artifact."},
 {"type":"mcq","q":"Inference tables for route-optimized endpoints are:",
  "opts":[("A","GA and instant"),("B","Public Preview; logs appear within ~1 hour and skip on some errors"),("C","Unsupported"),("D","Not UC-governed")],"ans":"B",
  "exp":"They're in Public Preview with ~1h log latency and error gaps."},
 {"type":"mcq","q":"Data residency for a deployed app is most directly controlled by:",
  "opts":[("A","Temperature"),("B","Region/workspace selection plus Unity Catalog governance"),("C","Chunk overlap"),("D","Few-shot count")],"ans":"B",
  "exp":"Region placement + UC governance control where data/models live."},
 {"type":"mcq","q":"Rising latency at peak hours is first addressed by:",
  "opts":[("A","Deleting the model"),("B","Scaling out (more concurrency/replicas) or provisioned throughput"),("C","Lowering embedding dimension"),("D","Removing guardrails")],"ans":"B",
  "exp":"Capacity-driven latency is fixed by scaling/reserving throughput."},
 {"type":"mcq","q":"To A/B test two prompt versions in production cleanly:",
  "opts":[("A","Edit the prompt by hand each request"),("B","Prompt-registry versions/aliases + endpoint traffic splitting + inference logging"),("C","Two companies"),("D","Disable MLflow")],"ans":"B",
  "exp":"Versioned prompts + traffic split + logging enable comparison."},
 {"type":"mcq","q":"A served model needs a specific library version. Ensure it by:",
  "opts":[("A","Hoping prod has it"),("B","Logging pip/conda requirements with the model"),("C","Installing on your laptop only"),("D","Ignoring versions")],"ans":"B",
  "exp":"MLflow captures the environment for serving to rebuild."},
 {"type":"mcq","q":"Which is a valid endpoint cost-control combination?",
  "opts":[("A","Scale-to-zero + AI Gateway rate limits"),("B","Max concurrency always on"),("C","Removing the signature"),("D","Raising temperature")],"ans":"A",
  "exp":"Scale-to-zero plus rate limits curb idle and runaway cost."},
 {"type":"mcq","q":"Inference tables can also store, for deployed agents:",
  "opts":[("A","MLflow traces"),("B","GPU firmware"),("C","Source repos"),("D","Embedding weights")],"ans":"A",
  "exp":"They can persist agent traces for monitoring/debugging."},
 {"type":"mcq","q":"Endpoint access restriction to one team is enforced by:",
  "opts":[("A","Endpoint permissions/ACLs (and AI Gateway policies)"),("B","Higher temperature"),("C","Higher k"),("D","More chunks")],"ans":"A",
  "exp":"Permissions/ACLs govern who can call the endpoint."},
 {"type":"open","q":"Explain the precise migration risk of legacy inference-table deprecation and the remediation steps.",
  "opts":None,"ans":"See explanation",
  "exp":"Pipelines/monitors built on the legacy schema break or stop receiving data after support ends, silently degrading monitoring. Remediate by enabling AI Gateway inference tables, updating unpacking/monitoring jobs to the new schema, and migrating historical data with Databricks' batch-migration notebook before the cutoff."},
 {"type":"open","q":"Describe how Unity Catalog lineage helps during an incident where answers cite wrong documents.",
  "opts":None,"ans":"See explanation",
  "exp":"Lineage links source tables → chunk/Delta tables → vector index → model → endpoint. Trace backward to find which source/version feeds the index, whether a recent load changed it, whether the index synced to wrong data, and which model/prompt is live — enabling targeted rollback (repoint alias, re-sync index, revert source load)."},
 {"type":"open","q":"Walk through assembling a RAG app into one deployable unit on Databricks.",
  "opts":None,"ans":"See explanation",
  "exp":"Build the chain (retriever over Vector Search + prompt + LLM endpoint + parser); log with MLflow (signature, input example, deps); register to UC; create a serving endpoint (scale-to-zero or provisioned as fit); enable inference tables + AI Gateway policies; gate promotion with automated eval; use aliases/traffic splitting for rollout/rollback."},
 {"type":"mcq","q":"Two facts explaining 429s + missing inference rows:",
  "opts":[("A","Logs aren't guaranteed on errors (incl. 429) AND 429 = rate limiting"),("B","429 means small model AND logs always complete"),("C","429 is success AND UC is off"),("D","Tables log everything AND 429 is DNS")],"ans":"A",
  "exp":"Error responses may skip logging; 429 is throttling."},
 {"type":"mcq","q":"The cheapest correct path to expose a registered model for real-time requests is:",
  "opts":[("A","Create a Model Serving endpoint for that version"),("B","Export to CSV"),("C","Delete it"),("D","Email it")],"ans":"A",
  "exp":"A serving endpoint exposes the registered model as a REST API."},
 {"type":"mcq","q":"Which is authoritative for cost across external/provisioned/pay-per-token endpoints?",
  "opts":[("A","Payload (inference) tables"),("B","Usage/system tables via AI Gateway usage tracking"),("C","The signature"),("D","Traces alone")],"ans":"B",
  "exp":"Usage/system tables aggregate tokens/requests for cost."},
 {"type":"mcq","q":"A model trained on Databricks is most easily deployed by:",
  "opts":[("A","Logging during training, registering to UC, starting a serving endpoint"),("B","Building a Docker image manually"),("C","Flask + Gunicorn on a VM"),("D","Pickling to a Volume")],"ans":"A",
  "exp":"The native MLflow→UC→Serving flow is least friction."},
 {"type":"mcq","q":"Guardrails at the gateway add, beyond UC permissions:",
  "opts":[("A","Runtime content controls (PII, unsafe content, injection, exfiltration)"),("B","Faster GPUs"),("C","Bigger embeddings"),("D","Lower temperature")],"ans":"A",
  "exp":"UC governs access; guardrails govern content/behavior at runtime."},
 {"type":"mcq","q":"Which does AI Gateway NOT guarantee?",
  "opts":[("A","Rate limiting"),("B","Usage tracking"),("C","Factual correctness / zero hallucination"),("D","Inference logging")],"ans":"C",
  "exp":"Guardrails can flag risk but don't guarantee correctness."},
 {"type":"mcq","q":"Provisioned throughput vs pay-per-token differ chiefly in:",
  "opts":[("A","Cost predictability and reserved capacity vs elastic per-use cost"),("B","Model accuracy"),("C","Embedding dimension"),("D","Chunk size")],"ans":"A",
  "exp":"Provisioned = reserved/predictable; pay-per-token = elastic/variable."},
])

M5 = ("Governance, Security & Privacy", 8, [
 {"type":"mcq","q":"Tenant/region data isolation that survives prompt injection must be enforced at:",
  "opts":[("A","The system prompt"),("B","The data/retrieval layer via UC row filtering under the caller's identity"),("C","The LLM's discretion"),("D","Client-side JS")],"ans":"B",
  "exp":"Only data-layer enforcement is injection-proof."},
 {"type":"mcq","q":"Column masking does what?",
  "opts":[("A","Restricts which rows are visible"),("B","Transforms/hides sensitive column values (e.g., show last 4 digits)"),("C","Trains the model"),("D","Sets temperature")],"ans":"B",
  "exp":"Column masking transforms sensitive field values."},
 {"type":"mcq","q":"Row filtering does what?",
  "opts":[("A","Masks column values"),("B","Restricts which rows a principal can access"),("C","Generates citations"),("D","Embeds text")],"ans":"B",
  "exp":"Row filtering limits accessible records by principal."},
 {"type":"mcq","q":"UC lineage is used for:",
  "opts":[("A","Showing data→model→endpoint dependencies for audit/impact analysis"),("B","Decoding tokens"),("C","Chunking"),("D","Streaming")],"ans":"A",
  "exp":"Lineage traces dependencies for audit and impact analysis."},
 {"type":"mcq","q":"PII in tickets should be handled by:",
  "opts":[("A","Embedding as-is"),("B","Detecting and masking/redacting before embedding and in logs"),("C","Raising temperature"),("D","Bigger chunks")],"ans":"B",
  "exp":"Detect+mask PII before it enters indexes/logs."},
 {"type":"mcq","q":"The decisive (often overlooked) check before commercial deployment of an open model is:",
  "opts":[("A","Benchmark score"),("B","License terms (commercial use + derivative/fine-tuned redistribution)"),("C","Parameter count"),("D","Model card color")],"ans":"B",
  "exp":"Licensing governs legal commercial/derivative use."},
 {"type":"mcq","q":"Why enforce access at the retrieval layer not generation?",
  "opts":[("A","Generation is slow"),("B","Once unauthorized data is in context it can leak via paraphrase; never retrieving it is the only robust guarantee"),("C","Retrieval is cheaper"),("D","Fewer tokens")],"ans":"B",
  "exp":"In-context data can leak indirectly; block at retrieval."},
 {"type":"mcq","q":"GDPR right-to-erasure in RAG requires:",
  "opts":[("A","A prompt instruction to ignore the person"),("B","Deleting source rows (stable IDs) so the synced index drops vectors, plus purging logs per retention"),("C","Lower temperature"),("D","Retraining the base model")],"ans":"B",
  "exp":"True erasure needs source deletion + index sync + log purge."},
 {"type":"mcq","q":"Secrets for a governed app belong in:",
  "opts":[("A","Databricks secret scopes with scoped access"),("B","The chain code"),("C","Chat messages"),("D","stdout logs")],"ans":"A",
  "exp":"Secret scopes keep credentials out of code/prompts/logs."},
 {"type":"mcq","q":"Logging full prompts/responses can violate compliance because:",
  "opts":[("A","It speeds inference"),("B","Payloads may contain PII/secrets, creating a governed copy subject to access/retention/residency rules"),("C","It lowers cost"),("D","It improves recall")],"ans":"B",
  "exp":"Sensitive payloads in logs are a new exposure surface."},
 {"type":"mcq","q":"Keep observability without the logging violation by:",
  "opts":[("A","Disabling all logging"),("B","Masking PII before/at logging, restricting table access via UC, retention/column masking, in-region storage"),("C","Logging to email"),("D","Raising temperature")],"ans":"B",
  "exp":"Mask, restrict, retain, and localize logged data."},
 {"type":"mcq","q":"A sales rep must see only their region's accounts even with a crafted prompt. Enforce via:",
  "opts":[("A","System-prompt rule"),("B","UC row filtering under the rep's identity"),("C","LLM self-censorship"),("D","Post-processing the answer")],"ans":"B",
  "exp":"Row filtering guarantees out-of-region rows are never retrieved."},
 {"type":"mcq","q":"Citations + UC lineage together provide:",
  "opts":[("A","Auditable provenance of which sources informed an answer"),("B","Lower latency"),("C","Bigger embeddings"),("D","Higher temperature")],"ans":"A",
  "exp":"They give traceable, auditable provenance."},
 {"type":"mcq","q":"Prompt injection is best mitigated by:",
  "opts":[("A","Trusting input"),("B","Delimiting untrusted input, validating it, guardrails, least-privilege tools"),("C","Higher temperature"),("D","Removing the system prompt")],"ans":"B",
  "exp":"Treat untrusted input as data; constrain and guard."},
 {"type":"mcq","q":"To restrict an endpoint to the support team:",
  "opts":[("A","Grant endpoint/model permissions to that group"),("B","Give everyone admin"),("C","Raise temperature"),("D","Disable lineage")],"ans":"A",
  "exp":"Scope permissions to the group (least privilege)."},
 {"type":"mcq","q":"An MCP-connected external tool is governed primarily by:",
  "opts":[("A","Unity Catalog row masking on the LLM"),("B","AI Gateway (identity, permissions, observability, guardrails) + Managed OAuth for credentials"),("C","The prompt"),("D","Client JS")],"ans":"B",
  "exp":"External tools are governed at the gateway/OAuth layer."},
 {"type":"mcq","q":"A UC function tool inherits governance because:",
  "opts":[("A","The LLM decides access"),("B","UC enforces permissions/lineage/masking on the function/data under the caller's identity"),("C","It's public"),("D","It ignores permissions")],"ans":"B",
  "exp":"UC functions run within the governance boundary."},
 {"type":"mcq","q":"For an EU-residency app using a third-party model, the residual risk to flag is:",
  "opts":[("A","Temperature"),("B","The external provider may process/transit data outside the EU regardless of your workspace region"),("C","Chunk size"),("D","Embedding dimension")],"ans":"B",
  "exp":"Verify the provider's processing region/terms; region-selecting your workspace isn't sufficient."},
 {"type":"mcq","q":"Guardrails complement UC by governing:",
  "opts":[("A","Who can access data (that's UC)"),("B","Runtime content/behavior (toxicity, PII, injection, exfiltration)"),("C","GPU type"),("D","Chunking")],"ans":"B",
  "exp":"UC = access; guardrails = content/behavior at inference."},
 {"type":"mcq","q":"An auditor wants the sources + model/prompt version behind a past answer. Provide:",
  "opts":[("A","Inference tables + UC lineage + prompt/model versioning"),("B","Higher temperature"),("C","A bigger embedder"),("D","Disabled logging")],"ans":"A",
  "exp":"Logged traffic, lineage, and versions reconstruct provenance."},
 {"type":"mcq","q":"Dynamic views in UC are used to:",
  "opts":[("A","Apply row/column-level security based on the querying principal"),("B","Train models"),("C","Stream tokens"),("D","Chunk documents")],"ans":"A",
  "exp":"Dynamic views enforce per-principal row/column security."},
 {"type":"mcq","q":"Least-privilege for a retrieval service means:",
  "opts":[("A","Grant broad admin"),("B","Grant only the catalogs/schemas/rows/columns it needs"),("C","No permissions at all"),("D","Public access")],"ans":"B",
  "exp":"Limit access to exactly what's required."},
 {"type":"mcq","q":"Which is NOT a governance reason but a distractor?",
  "opts":[("A","License compliance"),("B","Row/column security"),("C","Audit lineage"),("D","Raising temperature for safety")],"ans":"D",
  "exp":"Temperature is a decoding parameter, not a governance control."},
 {"type":"mcq","q":"Storing stable source IDs supports governance by enabling:",
  "opts":[("A","Targeted erasure and provenance"),("B","Faster GPUs"),("C","Lower temperature"),("D","Bigger embeddings")],"ans":"A",
  "exp":"IDs enable record-level deletion and traceability."},
 {"type":"mcq","q":"A response that paraphrases unauthorized retrieved data is a failure of:",
  "opts":[("A","Generation-layer trust (data should never have been retrieved)"),("B","Embedding size"),("C","Temperature"),("D","Chunk overlap")],"ans":"A",
  "exp":"Block at retrieval; in-context data can leak via paraphrase."},
 {"type":"mcq","q":"Which best protects logged inference data?",
  "opts":[("A","UC permissions + retention + column masking on the inference tables"),("B","Public sharing"),("C","No access controls"),("D","Emailing exports")],"ans":"A",
  "exp":"Govern the inference tables like any sensitive data."},
 {"type":"mcq","q":"Identity-first security for agents means:",
  "opts":[("A","Agents act with no identity"),("B","Actions run under a verifiable principal whose permissions cannot be bypassed"),("C","The LLM grants itself rights"),("D","Anonymous access")],"ans":"B",
  "exp":"Enforce permissions under a real, non-bypassable identity."},
 {"type":"mcq","q":"PII masking should occur:",
  "opts":[("A","Only after deployment incidents"),("B","At ingestion (before embedding) and on logged prompts/responses"),("C","Never"),("D","Only in the UI")],"ans":"B",
  "exp":"Mask early and in logs to prevent persistence of PII."},
 {"type":"mcq","q":"Which statement about licensing is correct?",
  "opts":[("A","All open models permit commercial use"),("B","License terms vary; some restrict commercial use or fine-tuned redistribution"),("C","Licenses don't matter"),("D","Stars determine rights")],"ans":"B",
  "exp":"Always verify the specific license terms."},
 {"type":"mcq","q":"The most robust place to stop unauthorized HR answers is:",
  "opts":[("A","Metadata/ACL filtering + UC permissions on the retrieved source"),("B","A bigger LLM"),("C","Higher k"),("D","More few-shot examples")],"ans":"A",
  "exp":"Enforce authorization at the data/retrieval layer."},
 {"type":"open","q":"Differentiate column masking, row filtering, and AI Gateway guardrails with one example each in a PII-sensitive RAG app.",
  "opts":None,"ans":"See explanation",
  "exp":"Column masking: SSN shown as ***-**-1234 at the data layer. Row filtering: a clinician sees only their patients' rows. Guardrails: block a response leaking a card number or detect injection at runtime. Masking/filtering keep unauthorized DATA from the model; guardrails keep unsafe CONTENT from the user."},
 {"type":"open","q":"Explain why prompt-level access rules are insufficient and what to use instead.",
  "opts":None,"ans":"See explanation",
  "exp":"Prompt rules are advisory and bypassable via injection or model error. Enforce at the data layer with UC permissions, row filters, column masks, and metadata ACL filtering at query time so unauthorized records are never retrieved or seen — auditable and robust independent of model behavior."},
 {"type":"open","q":"List the governance levers for an EU-residency deployment using a third-party model, and the residual risk.",
  "opts":None,"ans":"See explanation",
  "exp":"Levers: EU region/workspace; UC permissions/lineage/masking; route the model via an AI Gateway external endpoint for centralized logging/policy; guardrails against exfiltration; in-region inference-table location/retention. Residual risk: the third-party provider may process/transit data outside the EU — verify its processing region/contract; workspace region alone doesn't guarantee provider residency."},
 {"type":"mcq","q":"Which combination satisfies 'show which sources informed this answer'?",
  "opts":[("A","Citations/traceability + UC lineage"),("B","Higher temperature"),("C","Disabling logging"),("D","Bigger embeddings")],"ans":"A",
  "exp":"Citations plus lineage give source provenance."},
 {"type":"mcq","q":"A guardrail for prompt injection inspects:",
  "opts":[("A","Prompts/responses/tool calls at runtime for injection patterns"),("B","GPU temperature"),("C","Chunk size"),("D","Embedding dimension")],"ans":"A",
  "exp":"Injection guardrails operate on runtime content."},
 {"type":"mcq","q":"Unity Catalog governs which AI assets?",
  "opts":[("A","Tables, files, models, functions, connections, vector indexes"),("B","Only tables"),("C","Only models"),("D","Nothing AI-related")],"ans":"A",
  "exp":"UC governs a broad set of data and AI assets."},
 {"type":"mcq","q":"Right-to-erasure fails if you only:",
  "opts":[("A","Delete source rows and re-sync the index"),("B","Add a prompt instruction to ignore the person"),("C","Purge logs per retention"),("D","Remove stored vectors")],"ans":"B",
  "exp":"Prompt instructions don't delete persisted data."},
 {"type":"mcq","q":"Which is a privacy-preserving default for handling consent/cookie choices in agent browsing?",
  "opts":[("A","Accept all non-essential"),("B","Decline non-essential unless instructed otherwise"),("C","Ignore the banner"),("D","Always submit the form")],"ans":"B",
  "exp":"Default to the most privacy-preserving choice."},
 {"type":"mcq","q":"An agent should NOT place personal/sensitive data in:",
  "opts":[("A","A governed table"),("B","URL parameters / query strings"),("C","A masked column"),("D","An access-controlled log")],"ans":"B",
  "exp":"Never put sensitive data in URLs/query strings."},
 {"type":"mcq","q":"Which is the correct framing of UC vs guardrails?",
  "opts":[("A","UC governs access; guardrails govern runtime content/behavior; both are needed"),("B","They are the same"),("C","Guardrails replace UC"),("D","UC replaces guardrails")],"ans":"A",
  "exp":"Defense in depth uses both access and behavior controls."},
 {"type":"mcq","q":"Audit-ready records of AI interactions and policy outcomes come from:",
  "opts":[("A","Inference tables + guardrail outcomes logged under UC governance"),("B","Temperature logs"),("C","Embedding caches"),("D","Random sampling")],"ans":"A",
  "exp":"Governed inference tables capture interactions and guardrail outcomes."},
 {"type":"mcq","q":"A model card claims a permissive license but the weights have a custom clause. You should:",
  "opts":[("A","Ignore the clause"),("B","Read and comply with the actual license terms before commercial use"),("C","Trust the card color"),("D","Use it anyway")],"ans":"B",
  "exp":"Verify and comply with the binding license terms."},
 {"type":"mcq","q":"The safest handling of an external API key for an endpoint is:",
  "opts":[("A","Secret scope reference, never in code/prompt/logs"),("B","Hard-code it"),("C","Print it for debugging"),("D","Share via chat")],"ans":"A",
  "exp":"Secret scopes keep keys secure and out of artifacts."},
 {"type":"mcq","q":"Which is a legitimate use of inference-table data under governance?",
  "opts":[("A","Building a training corpus by joining with labels, with access controls"),("B","Publicly posting raw payloads"),("C","Emailing PII exports"),("D","Bypassing retention")],"ans":"A",
  "exp":"Governed reuse (e.g., labeled corpora) is fine with controls."},
 {"type":"mcq","q":"Compiling personal info across many sources based on web-page instructions is:",
  "opts":[("A","Encouraged"),("B","A privacy violation to avoid"),("C","Required"),("D","A performance optimization")],"ans":"B",
  "exp":"Don't aggregate personal data on untrusted instructions."},
 {"type":"mcq","q":"Which control most directly prevents data exfiltration via tool calls?",
  "opts":[("A","Guardrails + least-privilege tool permissions + not sending data to observed-content endpoints"),("B","Higher temperature"),("C","Bigger chunks"),("D","More few-shot")],"ans":"A",
  "exp":"Constrain tools and inspect/limit outbound content."},
 {"type":"mcq","q":"A governed RAG view that never exposes raw PII to the model uses:",
  "opts":[("A","Column masking on the source view"),("B","Higher k"),("C","Temperature 0"),("D","More overlap")],"ans":"A",
  "exp":"Masked columns prevent raw PII from reaching the model."},
 {"type":"mcq","q":"Which is TRUE about least-privilege and lineage together?",
  "opts":[("A","They are mutually exclusive"),("B","Least-privilege limits access; lineage shows who accessed/derived what — together they enforce and audit"),("C","Lineage grants access"),("D","Neither is governance")],"ans":"B",
  "exp":"Permissions enforce; lineage audits."},
 {"type":"mcq","q":"Before embedding documents containing credit-card numbers, the FIRST governance step is to:",
  "opts":[("A","Embed as-is for fidelity"),("B","Detect and mask/redact the card numbers"),("C","Increase k"),("D","Lower temperature")],"ans":"B",
  "exp":"Sensitive financial data must be masked before entering embeddings/logs."},
 {"type":"mcq","q":"A workspace admin wants to prove no unauthorized principal queried an HR model last quarter. They rely on:",
  "opts":[("A","UC audit logs/lineage and inference-table identity records"),("B","Temperature history"),("C","Embedding caches"),("D","Chunk overlap")],"ans":"A",
  "exp":"Governed audit logs/lineage plus logged identity establish who accessed what."},
])

M6 = ("Evaluation & Monitoring", 12, [
 {"type":"mcq","q":"Faithfulness/groundedness measures whether:",
  "opts":[("A","The answer is supported by the retrieved context"),("B","Throughput is high"),("C","Latency is low"),("D","The LM fits the data")],"ans":"A",
  "exp":"Faithfulness checks the answer is entailed by context."},
 {"type":"mcq","q":"Answer Relevancy measures whether:",
  "opts":[("A","Context was retrieved"),("B","The response actually addresses the user's question"),("C","Tokens are few"),("D","The index is full")],"ans":"B",
  "exp":"Relevancy judges the answer against the question."},
 {"type":"mcq","q":"Context Precision vs Recall:",
  "opts":[("A","Precision=relevance of retrieved; Recall=coverage of relevant info"),("B","Both measure latency"),("C","Both are generation metrics"),("D","They are identical")],"ans":"A",
  "exp":"Precision = signal-to-noise; recall = coverage."},
 {"type":"mcq","q":"To catch as many true positives as possible (minimize false negatives), optimize:",
  "opts":[("A","Recall"),("B","Precision"),("C","BLEU"),("D","ROUGE")],"ans":"A",
  "exp":"Recall minimizes false negatives."},
 {"type":"mcq","q":"On a 99%-majority imbalanced set, which metric is misleading?",
  "opts":[("A","Accuracy (a trivial majority predictor scores ~99%)"),("B","Recall"),("C","F1"),("D","Precision")],"ans":"A",
  "exp":"Accuracy hides failure on the minority class."},
 {"type":"mcq","q":"BLEU vs ROUGE:",
  "opts":[("A","BLEU precision-oriented (often MT); ROUGE recall-oriented (often summarization)"),("B","Identical"),("C","BLEU=latency, ROUGE=cost"),("D","Both measure retrieval")],"ans":"A",
  "exp":"BLEU precision/MT; ROUGE recall/summarization."},
 {"type":"mcq","q":"The function to run automated GenAI evaluation with scorers is:",
  "opts":[("A","mlflow.genai.evaluate()"),("B","print()"),("C","explode()"),("D","Photon")],"ans":"A",
  "exp":"mlflow.genai.evaluate runs scorers over outputs."},
 {"type":"mcq","q":"A custom LLM judge is created with:",
  "opts":[("A","make_judge()"),("B","collect_set()"),("C","ai_query()"),("D","pivot()")],"ans":"A",
  "exp":"make_judge defines an LLM-judge with a rubric."},
 {"type":"mcq","q":"To verify 'every answer cites a valid source ID present in context', use:",
  "opts":[("A","BLEU"),("B","A custom code-based scorer parsing/validating citations"),("C","Perplexity"),("D","Context Recall alone")],"ans":"B",
  "exp":"A deterministic rule needs a custom code scorer."},
 {"type":"mcq","q":"LLM-as-judge verbosity bias is mitigated by:",
  "opts":[("A","Clear rubric penalizing length, reference answers, human calibration"),("B","Trusting the judge"),("C","Self-judging"),("D","Higher judge temperature")],"ans":"A",
  "exp":"Tighten rubric, add references, calibrate to humans."},
 {"type":"mcq","q":"CLEARS stands for:",
  "opts":[("A","Correctness, Latency, Execution, Adherence, Relevance, Safety"),("B","Cost, Latency, Errors, Accuracy, Recall, Speed"),("C","Context, Length, Evidence, Answer, Rank, Score"),("D","None")],"ans":"A",
  "exp":"CLEARS = Correctness, Latency, Execution, Adherence, Relevance, Safety."},
 {"type":"mcq","q":"Which Lakehouse Monitoring profile fits a model/agent serving log over time?",
  "opts":[("A","InferenceLog"),("B","Snapshot"),("C","TimeSeries"),("D","Schema")],"ans":"A",
  "exp":"InferenceLog is for serving request logs with quality/drift."},
 {"type":"mcq","q":"A generic timestamped metrics table (not a serving log) uses which monitor?",
  "opts":[("A","TimeSeries"),("B","InferenceLog"),("C","Snapshot"),("D","Judge")],"ans":"A",
  "exp":"TimeSeries tracks metrics over a timestamp column."},
 {"type":"mcq","q":"A static current-state table profile uses:",
  "opts":[("A","Snapshot monitor"),("B","InferenceLog"),("C","TimeSeries"),("D","Judge")],"ans":"A",
  "exp":"Snapshot profiles the current state of a table."},
 {"type":"mcq","q":"Data drift vs concept drift:",
  "opts":[("A","Data=input distribution shift; Concept=input→correct-output relationship shift"),("B","Identical"),("C","Both fixed by temperature"),("D","Both require deleting the endpoint")],"ans":"A",
  "exp":"Data drift = inputs change; concept drift = the right answer changes."},
 {"type":"mcq","q":"Operational metrics for a GenAI endpoint include:",
  "opts":[("A","QPS, latency, error rate, cost/token usage"),("B","ROUGE only"),("C","Chunk size"),("D","Embedding dimension")],"ans":"A",
  "exp":"Throughput, latency, errors, and cost are operational signals."},
 {"type":"mcq","q":"High faithfulness + high context recall + LOW answer relevancy suggests:",
  "opts":[("A","Retrieval is broken"),("B","Generation/prompt-framing or query misinterpretation"),("C","Empty index"),("D","Embeddings too small")],"ans":"B",
  "exp":"Grounding/coverage are fine; the answer misses the question."},
 {"type":"mcq","q":"SME feedback is best incorporated via:",
  "opts":[("A","Ignoring it post-deploy"),("B","The Review App, building golden datasets and calibrating judges"),("C","BLEU only"),("D","Temperature by mood")],"ans":"B",
  "exp":"Review App feedback builds eval data and calibrates judges."},
 {"type":"mcq","q":"Why reuse the same scorers in dev and prod?",
  "opts":[("A","Apples-to-apples signal so regressions are detectable/attributable"),("B","To slow things down"),("C","To avoid Unity Catalog"),("D","To remove tracing")],"ans":"A",
  "exp":"Consistent metrics make regressions visible and attributable."},
 {"type":"mcq","q":"ROUGE alone is risky for summarization because:",
  "opts":[("A","It measures latency"),("B","It rewards overlap but can score a fluent, factually-wrong summary highly; add a faithfulness check"),("C","It guarantees accuracy"),("D","It is a retrieval metric")],"ans":"B",
  "exp":"Lexical overlap ≠ factual correctness."},
 {"type":"mcq","q":"Stable quality scorers but rising thumbs-down + p95 latency means:",
  "opts":[("A","All fine"),("B","Experience may be degrading (latency) and/or metrics miss user needs — investigate latency, broaden metrics"),("C","Lower temperature fixes latency"),("D","Delete dashboards")],"ans":"B",
  "exp":"Operational degradation and metric coverage gaps both warrant action."},
 {"type":"mcq","q":"A custom scorer can be:",
  "opts":[("A","Only an LLM judge"),("B","A code-based rule OR an LLM judge (make_judge)"),("C","Only BLEU"),("D","Only perplexity")],"ans":"B",
  "exp":"Custom scorers can be heuristic code or LLM judges."},
 {"type":"mcq","q":"Evaluation datasets in Unity Catalog provide:",
  "opts":[("A","Versioning, lineage, reproducible comparison across model/prompt versions"),("B","Faster GPUs"),("C","Lower temperature"),("D","Bigger embeddings")],"ans":"A",
  "exp":"UC eval datasets are versioned and governed for reproducibility."},
 {"type":"mcq","q":"MLflow Tracing primarily provides:",
  "opts":[("A","Span-level observability (inputs/outputs, latency, tokens, tool calls)"),("B","Quality scoring"),("C","Model training"),("D","Embeddings")],"ans":"A",
  "exp":"Tracing is observability; evaluation consumes traces."},
 {"type":"mcq","q":"To debug whether retrieval or generation caused a bad RAG answer, inspect:",
  "opts":[("A","The trace's retrieval span (chunks/scores) and LLM span (prompt/output)"),("B","Temperature logs"),("C","GPU serials"),("D","Chunk overlap")],"ans":"A",
  "exp":"Tracing pinpoints the failing step."},
 {"type":"mcq","q":"Agent Evaluation vs Agent Framework:",
  "opts":[("A","Evaluation measures quality; Framework builds/deploys"),("B","Same thing"),("C","Evaluation serves endpoints"),("D","Framework stores embeddings")],"ans":"A",
  "exp":"They are complementary but distinct."},
 {"type":"mcq","q":"LLM-as-judge should be validated against:",
  "opts":[("A","Itself"),("B","Human/SME labels (measure agreement, recalibrate)"),("C","Temperature"),("D","Chunk size")],"ans":"B",
  "exp":"Calibrate the judge against human labels."},
 {"type":"mcq","q":"Which is a quality (not operational) metric?",
  "opts":[("A","Faithfulness"),("B","QPS"),("C","Latency"),("D","Error rate")],"ans":"A",
  "exp":"Faithfulness is quality; QPS/latency/error are operational."},
 {"type":"mcq","q":"A monitor over an inference table first requires:",
  "opts":[("A","Nothing"),("B","Unpacking the JSON payloads per the endpoint schema (and optionally joining labels)"),("C","Raising temperature"),("D","Deleting metadata")],"ans":"B",
  "exp":"Unpack payloads before creating the monitor."},
 {"type":"mcq","q":"For summarization, the best metric pair is:",
  "opts":[("A","ROUGE + a faithfulness/factuality check"),("B","QPS + latency"),("C","Precision/Recall for classification"),("D","Cosine only")],"ans":"A",
  "exp":"Content overlap plus factuality covers summary quality."},
 {"type":"open","q":"You can run an LLM judge cheaply but it disagrees with SMEs ~20%. Describe a defensible production eval strategy using both.",
  "opts":None,"ans":"See explanation",
  "exp":"Use the judge for broad continuous coverage to flag issues/trends; calibrate against an SME-labeled golden set (measure agreement, refine the rubric); route low-confidence/high-stakes cases to SME review via the Review App; expand the golden set and recalibrate periodically; report metrics with the known judge error rate and never treat the judge as ground truth for high-stakes decisions without human spot-checks."},
 {"type":"open","q":"Explain CLEARS and why monitoring only Correctness is insufficient for an agent.",
  "opts":None,"ans":"See explanation",
  "exp":"CLEARS = Correctness, Latency, Execution, Adherence, Relevance, Safety. Only-Correctness misses latency/SLA regressions, tool-execution failures, drift from guidelines (adherence), off-topic answers (relevance), and unsafe/PII-leaking outputs (safety). An agent can be 'correct' on average while violating SLAs, mis-executing tools, or leaking data."},
 {"type":"open","q":"Design a RAG evaluation-dataset strategy: contents, relation to traces/Review App, and why version it in UC.",
  "opts":None,"ans":"See explanation",
  "exp":"Contents: representative + edge/adversarial questions with expected facts/answers (and supporting context). Build from real production traces and SME judgments via the Review App. Version in UC for reproducible, governed comparison across model/prompt versions with lineage — re-run the same dataset on each candidate, track quality over time, and prove which change caused a regression."},
 {"type":"mcq","q":"Production cost/token monitoring is exposed by:",
  "opts":[("A","AI Gateway usage tables + inference tables + Lakehouse Monitoring dashboards"),("B","Temperature logs"),("C","Embedding caches"),("D","Random sampling")],"ans":"A",
  "exp":"Usage/inference tables and monitoring dashboards surface cost."},
 {"type":"mcq","q":"Precision is the right priority when:",
  "opts":[("A","False positives are costly (you want few wrong positives)"),("B","False negatives are costly"),("C","You only care about fluency"),("D","Latency matters most")],"ans":"A",
  "exp":"Precision minimizes false positives."},
 {"type":"mcq","q":"F1 is useful because it:",
  "opts":[("A","Balances precision and recall"),("B","Measures latency"),("C","Measures cost"),("D","Measures fluency")],"ans":"A",
  "exp":"F1 is the harmonic mean of precision and recall."},
 {"type":"mcq","q":"The same judges/scorers across dev and prod is enabled by:",
  "opts":[("A","MLflow 3 evaluation/monitoring"),("B","Photon"),("C","Time travel"),("D","Two codebases")],"ans":"A",
  "exp":"MLflow 3 unifies eval and monitoring."},
 {"type":"mcq","q":"A drift alert should trigger a response of:",
  "opts":[("A","Ignore it"),("B","Investigate inputs/quality, refresh corpus/retrieval (data drift) or update ground truth/prompts/model (concept drift)"),("C","Raise temperature"),("D","Delete the endpoint")],"ans":"B",
  "exp":"Respond per drift type: refresh data vs update expectations/model."},
 {"type":"mcq","q":"Which is TRUE about LLM-as-judge cost/latency?",
  "opts":[("A","It is free and instant"),("B","It adds cost/latency and needs a strong judge model + calibrated prompts"),("C","It removes the need for metrics"),("D","It guarantees correctness")],"ans":"B",
  "exp":"Judges cost compute and require calibration."},
 {"type":"mcq","q":"Which signal best reveals user-perceived quality drift over time?",
  "opts":[("A","Feedback/thumbs trends + sampled quality scoring"),("B","Disk color"),("C","Cluster name"),("D","Notebook count")],"ans":"A",
  "exp":"Feedback trends and sampled scoring track perceived quality."},
 {"type":"mcq","q":"Perplexity measures:",
  "opts":[("A","Language-model fit/uncertainty, not task correctness"),("B","Retrieval recall"),("C","Latency"),("D","Cost")],"ans":"A",
  "exp":"Perplexity is an LM-fit metric, not a task-quality metric."},
 {"type":"mcq","q":"Combining automatic metrics with human review gives:",
  "opts":[("A","Scalable coverage (auto) + accurate calibration/edge-case judgment (human)"),("B","Slower everything"),("C","No benefit"),("D","Only cost")],"ans":"A",
  "exp":"Auto scales; humans calibrate and judge nuance."},
 {"type":"mcq","q":"Which is the right monitor for tracking a deployed RAG payload table's quality/drift?",
  "opts":[("A","InferenceLog (after unpacking payloads)"),("B","Snapshot on the raw blob"),("C","TimeSeries on raw JSON"),("D","No monitor possible")],"ans":"A",
  "exp":"InferenceLog on the unpacked table is correct."},
 {"type":"mcq","q":"Self-preference bias in LLM judging means:",
  "opts":[("A","The judge favors outputs resembling its own style/model"),("B","It favors shorter answers always"),("C","It ignores rubrics"),("D","It measures latency")],"ans":"A",
  "exp":"Judges can favor their own style — mitigate with calibration/diversity."},
 {"type":"mcq","q":"Which best detects a tool-execution failure in an agent?",
  "opts":[("A","The Execution dimension (CLEARS) via traces/scorers"),("B","BLEU"),("C","Perplexity"),("D","Embedding size")],"ans":"A",
  "exp":"Execution monitoring (traces) reveals tool/step failures."},
 {"type":"mcq","q":"A golden evaluation set should include:",
  "opts":[("A","Only easy questions"),("B","Representative plus hard/ambiguous/adversarial cases with expected answers"),("C","Random text"),("D","Only duplicates")],"ans":"B",
  "exp":"Edge and adversarial cases stress-test quality."},
 {"type":"mcq","q":"Which is the correct first action when a faithfulness scorer regresses in CI?",
  "opts":[("A","Promote anyway"),("B","Fail the build/block promotion and investigate"),("C","Delete the scorer"),("D","Raise temperature")],"ans":"B",
  "exp":"A regression below threshold should block promotion."},
 {"type":"mcq","q":"Which metric tells you per-request speed?",
  "opts":[("A","Latency"),("B","Faithfulness"),("C","ROUGE"),("D","Context recall")],"ans":"A",
  "exp":"Latency is per-request response time."},
 {"type":"mcq","q":"Why monitor cost alongside quality?",
  "opts":[("A","GenAI cost scales with tokens/traffic; balance quality vs spend and avoid budget blowouts"),("B","Cost never matters"),("C","To slow inference"),("D","To remove tracing")],"ans":"A",
  "exp":"Token-driven cost must be tracked against quality."},
 {"type":"mcq","q":"A RAG app shows LOW context recall but HIGH context precision. The likely issue is:",
  "opts":[("A","Retrieval returns clean but incomplete context (missing relevant chunks) — increase k, improve chunking, or rerank"),("B","The generator is too creative"),("C","Latency is high"),("D","The license is wrong")],"ans":"A",
  "exp":"High precision but low recall means what's retrieved is relevant but coverage is incomplete; fix retrieval breadth/chunking."},
])
